---
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
    exclude_paths:
    - public/
    - vendor/
  fixme:
    enabled: true
    exclude_patterns:
    - ".rubocop_enabled.yml"
    - ".rubocop.yml"
  rubocop:
    enabled: true
    config: '.rubocop.yml'

ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.js"
exclude_paths:
- config/
- db/
- spec/