menubar: false
language: es_MX
plugins: 
  ['advlist autolink lists link image charmap print preview anchor textcolor',
  'searchreplace visualblocks code fullscreen',
  'insertdatetime media table paste code help wordcount']
toolbar: 'undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | 
  bullist numlist outdent indent | removeformat | link image code | help'
